version: '2.0'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: "ng serve --host 0.0.0.0 --disable-host-check"
    volumes:
      - ./frontend/src:/usr/src/app/src

  postgres:
    image: postgres:9.5
    expose:
      - "5432"

  redis:
    image: redis
    expose:
      - "6379"
